package com.promptmanager.dao;

import java.io.File;
import java.sql.*;

/**
 * Manages the Database connection and schema initialisation.
 * The database file is stored in ~/.prompt-manager/prompts.db
 */
public class DatabaseManager {

    private static final String DB_DIR  = System.getProperty("user.home") + File.separator + ".prompt-manager";
    private static final String DB_NAME = "prompts.db";
    private static final String DB_PATH = DB_DIR + File.separator + DB_NAME;
    private static final String URL     = "jdbc:hsqldb:" + DB_PATH;

    private static DatabaseManager instance;
    private Connection connection;

    private DatabaseManager() throws SQLException, ClassNotFoundException {
        // Ensure the storage directory exists
        File dir = new File(DB_DIR);
        if (!dir.exists()) {
            dir.mkdirs();
        }
        Class.forName("org.hsqldb.jdbcDriver");
        connection = DriverManager.getConnection(URL);
//        // Enable WAL mode for better concurrency
//        try (Statement st = connection.createStatement()) {
//            st.execute("PRAGMA journal_mode=WAL");
//            st.execute("PRAGMA foreign_keys=ON");
//        }
        createSchema();
    }

    public static synchronized DatabaseManager getInstance() throws SQLException, ClassNotFoundException {
        if (instance == null || instance.connection.isClosed()) {
            instance = new DatabaseManager();
        }
        return instance;
    }

    public Connection getConnection() { return connection; }

    private void createSchema() throws SQLException {
        try (Statement st = connection.createStatement()) {
            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS prompts (
                    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    summary      VARCHAR(255) DEFAULT '' NOT NULL,
                    wording      VARCHAR(8192) DEFAULT '' NOT NULL,
                    date_created VARCHAR(255) NOT NULL,
                    comments     VARCHAR(4096) DEFAULT '' NOT NULL
                )
                """);

            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS stock_phrases (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    text       VARCHAR(255) DEFAULT '' NOT NULL,
                    sort_order INTEGER DEFAULT 0 NOT NULL
                )
                """);

            // Seed a few example stock phrases on first run
            ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM stock_phrases");
            if (rs.next() && rs.getInt(1) == 0) {
                st.executeUpdate("""
                    INSERT INTO stock_phrases (text, sort_order) VALUES
                        ('Now define a Business Requirements Document', 1),
                        ('Now generate a task registry with task number, specification of work, and filename', 2),
                        ('Summarise the above in bullet points', 3),
                        ('Now write unit tests for the code above', 4)
                    """);
            }
        }
    }

    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException ignored) {}
    }
}
